### ISSUE TITLE
How to deal with unused-expressions

### ISSUE THREAD

**Issue by jgrund** [jfmengels/eslint-plugin-fp#11]
Node.js is full of unused expressions.

For example, If I call `setHeader` on a `ClientRequest` I have a non-useful return.

There are things like `Eff` or `Io` to model side-effects; Is the best approach to disable eslint checking for unused expressions inside these monads?

**Comment by jfmengels** [comment]
Hi @jgrund!

You are right that Node.js has plenty of APIs that "kind of" makes use of unused expressions, and that's because Node, or JavaScript for that matter, was not made to be a full-fledged FP language / ecosystem.

You can't for instance use FP techniques with tools like `express` out of the box, but you're right that you can remove the side-effects by using Monads.
I haven't used them as much as I would have liked to (and never used `Io` or `Eff`), so take the rest of my comment with a grain of salt.

I think the approach you described is a very good one, if I understood you correctly: Create a new Monad type that wraps your HTTP requests tool and make its API stateless just like you'd expect from other monads.

In its implementation, you can then disable the ESLint rules that create errors. As long as you avoid things that would make your API not stateless and side-effectful, you are good to go. You are simply relocating your side-effectful code to a part where it is controlled and outside of your pure logic, and that's :+1:.

Let me know if my answer was not clear, or if I misunderstood you :)

**Comment by jgrund** [comment]
Yup, that was it; thanks :)

**Comment by jgrund** [comment]
One other thing of note, I wonder if using something like `Unit` from PureScript might be a good idea in tandem with this.

**Comment by jfmengels** [comment]
I have never tried PureScript, but if you go ahead and try it and it works nicely, let me know :)

**Comment by Couto** [comment]
I'm not a fp expert, really far from it, I only grasp the very basics, but how should we handle basic cases like `console.log` ? 

To wrap values in a monad/container/wtv seems to be a bit overkill, but then again, I might be missing something really basic due to my inexperience.
