### ISSUE TITLE
Is no-nill too strict?

### ISSUE THREAD

**Issue by mattiamanzati** [jfmengels/eslint-plugin-fp#9]
Hi all! Thanks for this awesome eslint plugin!
I can't use null in objects, is that a bug or an expected behaviour? How can I solve this?

```javascript
const defaultState = {
    token: null
}
export function reducer(state = defaultState, action){
    return state
}
```
```

/home/user/Scrivania/mercury-new/src/modules/auth/index.js
  3:12  error  Unallowed use of `null` or `undefined`  fp/no-nil


```

**Comment by jfmengels** [comment]
Hi @mattiamanzati!

That is expected behavior. The purpose is to have you avoid having `undefined` / `null` in your code as much as possible.
I did not describe in the rule's documentation how to code without it though, which I will add shortly.

The common alternative to use in functional programming is called `Maybe`, which you can find in some external packages, such as https://github.com/folktale/data.maybe.

The idea is globally this:
When you use functions that return possibly null/undefined, or target a field that can possibly be `null`, you instead return a `Maybe` object, that wrap the value you are accessing. You can apply functions on that object using (usually, depending on the implementation library) a `map` function, but which will all be ignored when the value is `Maybe.Nothing()` (the equivalent of nil).

```js
// When setting
const Maybe = require('some-maybe-library');

const defaultState = {
  token: Maybe.Nothing() // It has no value at the moment
}
export function reducer(state = defaultState, action) {
  if (action.type === 'SET_TOKEN') {
    return {
      ...state,
      token: Maybe.Just(action.token) // It now has a value, which will be `action.token`
    };
  }
  return state
}

// When accessing
const state = store.getState();

// I'm assuming for the example that this is some kind of HTTP Authentication token
const token = store.token
  .map(t => t.toLowerCase()) // Will not be applied if store.token === Maybe.Nothing()
  .map(t => `Bearer ${t}`) // Same here
  .orElse(() => ''); // `orElse` might have a different name depending on the library
```

End result:
If store.token equals `Xyz`, then token equals 'Bearer xyz'
If store.token was `Maybe.Nothing()`, then token equals ''.
The practical side of this method, is that you don't have to worry whether your value is null. Just `map` over it, and if it happened to be Maybe.Nothing(), it will stay like that until you call `getOr`.

I'm not sure this helped a lot, as I'm pretty sure I didn't explain it properly. I'll try to find a nice and friendly `Maybe` explanation and put that into the rule's documentation.
Let me know if you have other questions, or you want me to explain some parts better or in more detail :)

**Comment by mattiamanzati** [comment]
Thanks for your explanation! Am I wrong or Maybe have something to deal with Monads? I think I have to find out some article on that! Thanks for your reply!

**Comment by jfmengels** [comment]
Yes, Maybe is a monad. I recommend reading this (relatively short) book https://github.com/MostlyAdequate/mostly-adequate-guide, which I thought was pretty good last time I read it. [This one](https://github.com/getify/functional-light-js) is pretty nice too, but the section about monads and Maybe is not yet written. I'll try to find a nice short article dealing with Maybe.

**Comment by mattiamanzati** [comment]
Thanks again for the links!

**Comment by avalanche1** [comment]
I use `map()` extensively with curly braces - which requires a `return` statement. Can we add a sub-rule for fp/no-nil to exclude `map()` from linting?
